// Fix A (Important, review round 2): verify used to score NOTHING for a
// template-centric migration — kind:"template" outputs were always skipped
// (correctly, on their own — a literal `{{ post.title }}` placeholder in a
// browser is noise, not signal) but nothing ever rendered them with real
// data first the way Task 8 did by hand. This module is that missing step:
// resolve which sample/original a template output belongs to (pure —
// resolveScoringPlan), harvest real per-sample data for it (sampleHarvest.mjs)
// mapped onto CONTENT-MODEL.md's field contract (contentModelFields.mjs),
// assemble a JSON render context (pure — buildRenderContext), and shell out
// to the vendored twig/twig via php (src/php/render-harness.php) to produce
// real, screenshot-able HTML. verify.mjs then screenshots/diffs it exactly
// like a page. Every failure mode (no pagetypes.json entry, no
// CONTENT-MODEL.md section, no usable sample, a Twig error) degrades to
// "not scored" with the reason surfaced — never a crash, never a fake 0.

import { readFile, writeFile, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import { urlToSlug } from "./slug.mjs";
import { pickRepresentativeCaptureUrl } from "./siteChrome.mjs";
import { parseContentModelForType } from "./contentModelFields.mjs";
import { harvestPageData, harvestArchiveItems, harvestMenuItems, harvestWooProduct } from "./sampleHarvest.mjs";

// The plugin's own vendored twig/twig — canai-replicate lives at
// <plugin>/ai/canai-replicate/, so this is <plugin>/vendor/autoload.php.
// Exported (and used as every render function's default) so callers like
// verify.mjs don't each need to re-derive the same relative path; tests
// override it explicitly since a test fixture's "runDir" has nothing to do
// with where the real plugin vendor dir lives.
export const DEFAULT_VENDOR_AUTOLOAD_PATH = path.resolve(
  new URL(".", import.meta.url).pathname,
  "../../../vendor/autoload.php",
);

// Woo `kind`s that are one WooCommerce-owned structural page (mirrors
// transform.mjs's WOO_STRUCTURAL_KINDS 1:1 — kept as its own small copy
// here, not re-exported/imported from transform.mjs, because the two
// modules read this constant for two different purposes: transform.mjs
// decides which PROMPT to hand an authoring agent; this module decides
// whether attempting a render is in scope at all, and duplicating six
// string literals is cheaper to keep in sync than a cross-module import
// whose failure mode — an out-of-date copy — is easy to catch (see
// twigRender.test.mjs, which pins all six against the real transform.mjs
// export).
export const WOO_STRUCTURAL_KINDS = new Set([
  "woo:shop",
  "woo:cart",
  "woo:checkout",
  "woo:my-account",
  "woo:order-received",
  "woo:product-category",
]);

// A generated chrome partial (output/templates/header.html /footer.html —
// see prompts/transform-chrome.md) is a Twig FRAGMENT, not a standalone
// document — it has no <!DOCTYPE>/<head>/<body> and is never meant to be
// opened or scored on its own; it only ever renders spliced into a page/
// template via {{ wpcanai_template('header'|'footer') }}. Scoring one of
// these standalone as if it were a template would be meaningless (there is
// no "original screenshot" of a bare header fragment) — collectOutputs
// still lists it (it's a real .html file under output/templates/), so
// verify.mjs filters it out with this before attempting anything.
export function isChromePartial(file) {
  return file === "header.html" || file === "footer.html";
}

// Does this HTML contain literal Twig delimiters? Used to decide whether a
// kind:"page" output (a one-off page) needs the Twig-render pre-pass before
// screenshotting. Pre-Fix-B, a one-off page was always pure static HTML
// (canai-prepare's original self-contained-preview philosophy) — Fix B's
// updated prompts/transform.md now has pages include shared chrome via
// {{ wpcanai_template('header') }}, so a FUTURE page can legitimately
// contain Twig syntax; a page generated before that change (e.g.
// wpdev.xcloudzen.com's existing output, not regenerated by this task) has
// none, and keeps going through the original raw-file-open path completely
// unaffected — this predicate is what tells the two apart, automatically.
export function containsTwigSyntax(html) {
  return /\{\{|\{%/.test(String(html ?? ""));
}

// A template output file's slug follows transform.mjs's own naming
// convention: `${type.name}-single.html` / `${type.name}-archive.html` for
// a repeating type, or bare `${type.name}.html` (no suffix) for a Woo
// structural page. Recovering (typeName, variant) from that convention is
// the ONE thing resolveScoringPlan needs from the filename; everything else
// it needs comes from the matching pagetypes.json entry.
export function classifyTemplateFilename(file) {
  const slug = file.replace(/\.html$/, "");
  if (slug.endsWith("-single")) return { typeName: slug.slice(0, -"-single".length), variant: "single" };
  if (slug.endsWith("-archive")) return { typeName: slug.slice(0, -"-archive".length), variant: "archive" };
  return { typeName: slug, variant: "structural" };
}

// The core decision function: given a parsed pagetypes.json and one
// template output's filename, decide WHAT this template needs rendered
// (which sample(s) supply the data, which capture supplies the "original"
// screenshot to diff against) — or, honestly, that it's out of scope or
// unresolvable. Pure: no fs access, no subprocess, fully deterministic from
// its inputs — this is what makes it exhaustively unit-testable.
//
// Returns one of:
//   { ok: false, reason: string }
//   { ok: true, variant: "single"|"archive", typeName, kind, dataUrl,
//     originalUrl, siblingUrls }
export function resolveScoringPlan({ pagetypes, file }) {
  const { typeName, variant } = classifyTemplateFilename(file);
  const types = Array.isArray(pagetypes?.types) ? pagetypes.types : [];
  const type = types.find((t) => t?.name === typeName);
  if (!type) {
    return { ok: false, reason: `no pagetypes.json type entry named "${typeName}" (looked for it from output file "${file}")` };
  }

  if (variant === "structural" || WOO_STRUCTURAL_KINDS.has(type.kind)) {
    return {
      ok: false,
      reason:
        `Woo structural page (kind: ${type.kind}) — WooCommerce owns this page's state ` +
        `(cart/checkout/account/shop grid), there is no CONTENT-MODEL.md field contract to ` +
        `render it from; rendering is not attempted here — review it structurally instead`,
    };
  }

  if (variant === "single") {
    const samples = Array.isArray(type.samples) ? type.samples.filter(Boolean) : [];
    if (samples.length === 0) {
      return { ok: false, reason: `type "${typeName}" has no sample URLs in pagetypes.json` };
    }
    return {
      ok: true,
      variant: "single",
      typeName,
      kind: type.kind,
      dataUrl: samples[0],
      originalUrl: samples[0],
      siblingUrls: samples.slice(1),
    };
  }

  // variant === "archive"
  if (!type.archiveUrl) {
    return { ok: false, reason: `type "${typeName}" has no archiveUrl in pagetypes.json` };
  }
  const samples = Array.isArray(type.samples) ? type.samples.filter(Boolean) : [];
  return {
    ok: true,
    variant: "archive",
    typeName,
    kind: type.kind,
    dataUrl: type.archiveUrl,
    originalUrl: type.archiveUrl,
    siblingUrls: samples,
  };
}

// Assemble the JSON-able render context render-harness.php reads. Pure —
// takes already-harvested/already-read data, produces a plain object ready
// for JSON.stringify. Kept separate from the fs/subprocess orchestration
// below so the exact shape the PHP side depends on is unit-testable without
// invoking php at all.
export function buildRenderContext({
  vendorAutoloadPath,
  siteUrl,
  mainTemplateSource,
  headerTemplateSource = null,
  footerTemplateSource = null,
  post = null,
  posts = null,
  enrichedPost = null,
  relatedPosts = [],
  menus = {},
}) {
  return {
    vendorAutoloadPath,
    siteUrl,
    mainTemplateSource,
    headerTemplateSource,
    footerTemplateSource,
    context: { post, posts },
    enrichedPost,
    relatedPosts,
    menus,
  };
}

async function exists(p) {
  try {
    await readFile(p);
    return true;
  } catch {
    return false;
  }
}

// Shell out to render-harness.php with `contextObj` (see buildRenderContext)
// and return either the rendered HTML or a surfaced error message — never
// throws. Writes the context to a scratch temp dir (cleaned up on the way
// out) rather than piping over stdin, so a large template source (real
// generated templates run 15-20KB) can't hit an OS pipe-buffer limit.
export async function renderViaPhp({ contextObj, phpBin = "php" }) {
  const harnessPath = path.resolve(new URL(".", import.meta.url).pathname, "php/render-harness.php");
  const scratchDir = await mkdtemp(path.join(tmpdir(), "canai-replicate-twigrender-"));
  const contextPath = path.join(scratchDir, "context.json");
  const outputPath = path.join(scratchDir, "output.html");
  try {
    await writeFile(contextPath, JSON.stringify(contextObj));
    const result = await new Promise((resolve) => {
      const proc = spawn(phpBin, [harnessPath, contextPath, outputPath], { stdio: ["ignore", "pipe", "pipe"] });
      let stderr = "";
      proc.stdout.on("data", () => {});
      proc.stderr.on("data", (d) => (stderr += d.toString()));
      proc.on("error", (e) => resolve({ code: -1, stderr: `could not run \`${phpBin}\`: ${e.message}` }));
      proc.on("close", (code) => resolve({ code, stderr }));
    });
    if (result.code !== 0) {
      return { ok: false, error: result.stderr.trim() || `php exited ${result.code}` };
    }
    const html = await readFile(outputPath, "utf8");
    return { ok: true, html };
  } catch (e) {
    return { ok: false, error: e.message };
  } finally {
    await rm(scratchDir, { recursive: true, force: true }).catch(() => {});
  }
}

// Load the site's representative-capture nav links (siteChrome.mjs — the
// SAME capture prompts/transform-chrome.md picked when authoring header.html/
// footer.html) as get_menu() stub data. Computed once per verify run and
// reused across every template/page render, so every render agrees on the
// same nav — mirroring how the real site only has one actual WordPress menu.
// Degrades to {} (both locations empty) when there's no representative
// capture or its content.json is missing/unreadable — get_menu() then just
// returns [] in the harness, which is a graceful "no data available", not a
// crash.
export async function loadRepresentativeMenus({ runDir, pagetypes }) {
  const repUrl = pickRepresentativeCaptureUrl(pagetypes);
  if (!repUrl) return {};
  const capDir = path.join(runDir, "captures", urlToSlug(repUrl));
  try {
    const contentJson = JSON.parse(await readFile(path.join(capDir, "content.json"), "utf8"));
    return {
      wpcanai_primary: harvestMenuItems(contentJson?.header?.links),
      wpcanai_footer: harvestMenuItems(contentJson?.footer?.links),
    };
  } catch {
    return {};
  }
}

async function readJsonIfExists(p) {
  try {
    return JSON.parse(await readFile(p, "utf8"));
  } catch {
    return null;
  }
}

async function readTextIfExists(p) {
  try {
    return await readFile(p, "utf8");
  } catch {
    return null;
  }
}

// Full orchestration for one output/templates/<...>.html entry: resolve
// what it needs (resolveScoringPlan), read CONTENT-MODEL.md + the sample
// capture(s), harvest real data, load chrome partials, render via PHP.
// Returns:
//   { rendered: false, reason: string }                 — degrade, surfaced
//   { rendered: true, html: string, originalPng: string } — ready to screenshot+diff
// Never throws — every fs read / parse / php call is guarded, with the
// concrete reason threaded through to the caller (verify.mjs's report).
export async function renderTemplateForScoring({ runDir, file, siteUrl, phpBin = "php", vendorAutoloadPath = DEFAULT_VENDOR_AUTOLOAD_PATH }) {
  const pagetypes = await readJsonIfExists(path.join(runDir, "pagetypes.json"));
  if (!pagetypes) {
    return { rendered: false, reason: "pagetypes.json missing or invalid — cannot resolve which sample this template belongs to" };
  }

  const plan = resolveScoringPlan({ pagetypes, file });
  if (!plan.ok) return { rendered: false, reason: plan.reason };

  const contentModelMd = await readTextIfExists(path.join(runDir, "CONTENT-MODEL.md"));
  if (!contentModelMd) {
    return { rendered: false, reason: `CONTENT-MODEL.md not found at ${path.join(runDir, "CONTENT-MODEL.md")}` };
  }
  const parsed = parseContentModelForType(contentModelMd, plan.typeName);
  if (!parsed) {
    return { rendered: false, reason: `CONTENT-MODEL.md has no section for type "${plan.typeName}"` };
  }

  // Harvest visibility (smittenkitchen.com dogfood, defect #2): field
  // harvesting used to be COMPLETELY silent — a CONTENT-MODEL.md whose
  // field-table rows didn't match the parser's expectations rendered the
  // template with every custom field empty and said nothing, anywhere,
  // about why. Now every parse says exactly what it harvested, and every
  // row the (now-tolerant — see contentModelFields.mjs) parser still had
  // to skip is surfaced loudly, including the always-wrong "a field table
  // exists but yielded zero fields" case.
  for (const w of parsed.warnings ?? []) {
    process.stderr.write(`  ! CONTENT-MODEL.md (${plan.typeName}): ${w}\n`);
  }
  const fieldNames = parsed.fields.map((f) => f.name).join(", ");
  const taxonomyNames = parsed.taxonomies.map((t) => t.name).join(", ");
  process.stderr.write(
    `  harvested ${parsed.fields.length} field(s) for ${plan.typeName}` +
      (fieldNames ? `: ${fieldNames}` : "") +
      (parsed.taxonomies.length ? `; ${parsed.taxonomies.length} taxonomy(ies): ${taxonomyNames}` : "") +
      "\n",
  );

  const dataSlug = urlToSlug(plan.dataUrl);
  const dataContentJson = await readJsonIfExists(path.join(runDir, "captures", dataSlug, "content.json"));
  if (!dataContentJson) {
    return { rendered: false, reason: `no capture content.json for ${plan.dataUrl} (slug "${dataSlug}") — capture may have failed` };
  }
  const originalPng = path.join(runDir, "captures", dataSlug, "screenshot.png");

  const mainTemplateSource = await readTextIfExists(path.join(runDir, "output", "templates", file));
  if (mainTemplateSource === null) {
    return { rendered: false, reason: `template file not found on disk: ${file}` };
  }

  const headerTemplateSource = await readTextIfExists(path.join(runDir, "output", "templates", "header.html"));
  const footerTemplateSource = await readTextIfExists(path.join(runDir, "output", "templates", "footer.html"));
  const menus = await loadRepresentativeMenus({ runDir, pagetypes });

  const siblingContentJsons = [];
  for (const url of plan.siblingUrls) {
    const cj = await readJsonIfExists(path.join(runDir, "captures", urlToSlug(url), "content.json"));
    if (cj) siblingContentJsons.push(cj);
  }

  let contextArgs;
  if (plan.kind === "woo:product") {
    const wc = harvestWooProduct({ contentJson: dataContentJson, leftoverFields: parsed.fields });
    contextArgs = {
      post: { ID: 1, post_title: wc.name, post_name: urlToSlug(plan.dataUrl), wc },
      enrichedPost: { ID: 1, post_title: wc.name, fields: wc.fields },
      relatedPosts: harvestArchiveItems(siblingContentJsons),
    };
  } else if (plan.variant === "archive") {
    // Real bug, caught by actually looking at the rendered screenshot (not
    // just trusting green tests): `dataContentJson` here is the ARCHIVE
    // LISTING page's own capture (used above to resolve `originalPng`) —
    // its content describes the listing page itself (intro copy, and on at
    // least one real site a mis-tagged/oversized "hero"), not an individual
    // item that belongs in the `{% for post in posts %}` card grid. Only
    // `siblingContentJsons` (the type's own samples) are genuine posts;
    // including the archive's own page data as a fake extra "post" produced
    // a card with garbage heading/image text pulled from listing-page chrome.
    contextArgs = {
      posts: harvestArchiveItems(siblingContentJsons),
    };
  } else {
    const harvested = harvestPageData({ contentJson: dataContentJson, fields: parsed.fields, taxonomies: parsed.taxonomies });
    const postTypeSlug = parsed.postTypeSlug || plan.typeName;
    contextArgs = {
      post: { ID: 1, post_title: harvested.post_title, post_content: harvested.post_content, post_excerpt: harvested.post_excerpt, post_name: dataSlug, post_type: postTypeSlug },
      enrichedPost: {
        ID: 1,
        post_title: harvested.post_title,
        post_content: harvested.post_content,
        post_excerpt: harvested.post_excerpt,
        post_name: dataSlug,
        fields: harvested.fields,
        featured_image: harvested.featured_image,
        taxonomy_items: harvested.taxonomy_items,
      },
      relatedPosts: harvestArchiveItems(siblingContentJsons),
    };
  }

  const contextObj = buildRenderContext({
    vendorAutoloadPath,
    siteUrl,
    mainTemplateSource,
    headerTemplateSource,
    footerTemplateSource,
    menus,
    ...contextArgs,
  });

  const result = await renderViaPhp({ contextObj, phpBin });
  if (!result.ok) return { rendered: false, reason: `Twig render failed: ${result.error}` };
  return { rendered: true, html: result.html, originalPng };
}

// Lighter-weight sibling for kind:"page" outputs that opted into shared
// chrome (Fix B): no CONTENT-MODEL.md, no per-sample harvesting — the page
// already carries its own real, hardcoded content, the ONLY unresolved Twig
// in it is the two {{ wpcanai_template('header'|'footer') }} calls. Only
// ever invoked after containsTwigSyntax(html) says there's something to
// resolve; a legacy pure-static page never reaches this at all.
export async function renderPageChromeForScoring({ runDir, mainTemplateSource, siteUrl, phpBin = "php", vendorAutoloadPath = DEFAULT_VENDOR_AUTOLOAD_PATH }) {
  const pagetypes = await readJsonIfExists(path.join(runDir, "pagetypes.json"));
  const headerTemplateSource = await readTextIfExists(path.join(runDir, "output", "templates", "header.html"));
  const footerTemplateSource = await readTextIfExists(path.join(runDir, "output", "templates", "footer.html"));
  const menus = pagetypes ? await loadRepresentativeMenus({ runDir, pagetypes }) : {};

  const contextObj = buildRenderContext({
    vendorAutoloadPath,
    siteUrl,
    mainTemplateSource,
    headerTemplateSource,
    footerTemplateSource,
    menus,
  });
  const result = await renderViaPhp({ contextObj, phpBin });
  if (!result.ok) return { rendered: false, reason: `Twig render failed: ${result.error}` };
  return { rendered: true, html: result.html };
}
